#ifndef DEF_H
#define DEF_H

#define WINDOW_HEIGHT 170
#define WINDOW_WIDTH 280
#define WINDOW_RESIZE_HEIGHT 130

#define AUXILIARY_BUTTON_SIZE 20

#define MAX_COUNT_MINUTES_TIME 1000 //MINUTES
#define MAX_COUNT_SECONDS_TIME 59
#define MAX_COUNT_MILLSEC_TIME 999
#define TIMER_INTERVAL 10 //MILLSECONDS

#define TASKS_FILENAME "tasks"

#endif // DEF_H
